apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jmeter-job
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
        template:
            metadata:
              labels:
                app: jmeter
            spec:
                volumes:
                    - name: volume-1
                      persistentVolumeClaim:
                        claimName: test-jmeter
                containers:
                    - name: test-jmeter
                      image: 'juankanh/jmeter-docker:latest'
                      command: [ "jmeter","-p","custom.properties","-n","-t","testing.jmx" ]
                      resources: {}
                      volumeMounts:
                        - name: volume-1
                          mountPath: /result
                      env:
                        - name: custom.properties
                          valueFrom:
                            configMapKeyRef:
                              name: properties
                              key: custom.properties
                        - name: testing.jmx
                          valueFrom:
                            configMapKeyRef:
                              name: properties
                              key: testing.jmx
                        - name: var.csv
                          valueFrom:
                            configMapKeyRef:
                               name: properties
                               key: var.csv
                restartPolicy: Never