apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-jmeter
  template:
    metadata:
      labels:
        app: test-jmeter
    spec:
        volumes:
            - name: volume-1
              persistentVolumeClaim:
                claimName: test-jmeter
            - name: volume-2
              configMap:
                name: properties
        containers:
            - name: test-jmeter
              image: 'juankanh/jmeter-docker:latest'
              resources: {}
              volumeMounts:
                - name: volume-1
                  mountPath: /result
                - name: volume-2
                  mountPath: /configmap
              env:
                - name: PROPERTIES
                  valueFrom:
                    configMapKeyRef:
                      name: properties
                      key: custom.properties
                - name: TESTS
                  valueFrom:
                    configMapKeyRef:
                      name: properties
                      key: testing.jmx
                - name: VARS
                  valueFrom:
                    configMapKeyRef:
                        name: properties
                        key: var.csv
