kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-jmeter
  creationTimestamp: null
  labels:
    app: test-jmeter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}