kind: Service
apiVersion: v1
metadata:
  name: publisher
  creationTimestamp: null
  labels:
    app: publisher
spec:
  ports:
    - port: 53034
      targetPort: 0
  selector:
    app: publisher
  type: ClusterIP
status:
  loadBalancer: {}