kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-python
  creationTimestamp: null
  labels:
    app: app-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: 'juankanh/myimagenpyhton:latest'
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources: {}
  strategy: {}
status: {}