kind: Service
apiVersion: v1
metadata:
  name: app-python
  creationTimestamp: null
  labels:
    app: app-python
spec:
  ports:
    - port: 5000
      targetPort: 0
  selector:
    app: app-python
  type: ClusterIP
status:
  loadBalancer: {}